import datetime,hashlib,json,os,pathlib,subprocess,sys,time
root=pathlib.Path(__file__).resolve().parents[2];variant,revision=sys.argv[1:];assert variant in ['external','bundled'];assert revision in ['274','289'];out=root/'docs/compat/evidence/navigation-load';app=root/f'.superpowers/navigation-proof/Nav {variant.title()} Proof.app';binary=app/'Contents/MacOS/nav_origin_probe';receipt=json.loads((out/f'build-isolated-{variant}-nav_origin_probe.json').read_text());assert receipt['isolated_build'];assert hashlib.sha256(binary.read_bytes()).hexdigest()==receipt['binary_sha256'];stem=out/f'probe-{variant}-{revision}';assert not stem.with_suffix('.log').exists();engine=pathlib.Path('/Users/acfrazier/experiments')/('Server/engine' if revision=='274' else 'lostcity-289/engine')
command=[str(binary),'--profile',f'local-{revision}','--revision',revision,'--engine',str(engine),'--unpack',str(root/f'.superpowers/navigation-proof/unpack-{variant}-{revision}')]
if variant=='external':command += ['--nav-pack',str(app/f'Contents/Resources/nav/{revision}/274bot.navpack')]
env=dict(os.environ);env.pop('NAV_PACK',None);env.pop('NAV_FLAGS',None);env.update(PROBE_EXPECT_ORIGIN=variant,PROBE_MUTATE_OWNED_PACK='1')
record=dict(command=command,started_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),binary_sha256=receipt['binary_sha256'],isolated_build=True,variant=variant,revision=int(revision),source_receipt=str(out/f'private-source-{variant}.json'),private_environment={k:env[k] for k in ['PROBE_EXPECT_ORIGIN','PROBE_MUTATE_OWNED_PACK']},elapsed_is_not_performance_measurement=True);before=time.monotonic()
with stem.with_suffix('.log').open('w') as log:
 p=subprocess.Popen(command,cwd=root,env=env,stdout=log,stderr=subprocess.STDOUT);record['pid']=p.pid;stem.with_suffix('.process.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record),flush=True);code=p.wait()
record.update(exit_code=code,finished_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),elapsed_seconds=round(time.monotonic()-before,3),log_sha256=hashlib.sha256(stem.with_suffix('.log').read_bytes()).hexdigest());stem.with_suffix('.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record),flush=True);sys.exit(code)
