import datetime,hashlib,json,os,pathlib,subprocess,sys,time
root=pathlib.Path(__file__).resolve().parents[2]; variant=sys.argv[1]; assert variant in ('external','bundled'); revision='289'; out=root/'docs/compat/evidence/navigation-load'; app=root/f'.superpowers/navigation-proof/Nav {variant.title()} Proof.app'; binary=app/'Contents/MacOS/startup_watch'; build=json.loads((out/f'build-isolated-{variant}-startup_watch.json').read_text()); assert build['isolated_build']; assert hashlib.sha256(binary.read_bytes()).hexdigest()==build['binary_sha256']; stem=out/f'native-{variant}-289'; assert not stem.with_suffix('.log').exists(); private=root/f'.superpowers/navigation-proof/ui-{variant}'; private.mkdir(exist_ok=True)
command=[str(binary),'--profile','local-289','--revision','289','--host','127.0.0.1','--port','44594','--asset-host','127.0.0.1','--http-port','1080','--engine','/Users/acfrazier/experiments/lostcity-289/engine','--vault',str(private/'empty-first-run.vault'),'--unpack',str(private/'unpack')]
if variant=='external': command+=['--nav-pack',str(app/'Contents/Resources/nav/289/274bot.navpack')]
env=dict(os.environ)
for key in ['NAV_PACK','NAV_FLAGS','BOT_VAULT_PASS','BOT_LIVE']: env.pop(key,None)
env.update(BOT_DEBUG='1'); before=time.monotonic(); record=dict(command=command,started_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),binary_sha256=build['binary_sha256'],isolated_build=True,variant=variant,revision=289,scope='Native startup UI only; no bot account or login',elapsed_is_not_performance_measurement=True)
with stem.with_suffix('.log').open('w') as log:
 p=subprocess.Popen(command,cwd=root,env=env,stdout=log,stderr=subprocess.STDOUT); record['pid']=p.pid; stem.with_suffix('.process.json').write_text(json.dumps(record,indent=2)+'\n'); print(json.dumps(record),flush=True); code=p.wait()
record.update(exit_code=code,finished_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),elapsed_seconds=round(time.monotonic()-before,3),log_sha256=hashlib.sha256(stem.with_suffix('.log').read_bytes()).hexdigest()); stem.with_suffix('.json').write_text(json.dumps(record,indent=2)+'\n'); print(json.dumps(record),flush=True); sys.exit(code)
