import collections,hashlib,json,pathlib,datetime,subprocess
root=pathlib.Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],cwd=pathlib.Path(__file__).parent,text=True).strip());e=root/'docs/compat/evidence/platform-isolated';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();result={}
w=e/'windows-native-6c7075ce';r=json.loads((w/'receipt.json').read_text());assert r['exit_code']==0 and not r['runtime_errors']
for name,h in r['evidence_files'].items():assert sha(w/name)==h,name
b=json.loads((e/'windows-6c7075ce/platform-build.json').read_text());assert b['isolated_build'] and b['target_started_empty'];job=next(j for j in b['jobs'] if j['name']=='catalog_watch');assert job['exit_code']==0 and job['binary_sha256']==r['binary_sha256']
snap_path=next((w/'shots').rglob('*.json'));snap=json.loads(snap_path.read_text());assert snap['ingame'] and snap['scene_state']==2
inv={x['def']['id']:x['count'] for x in snap['inventory']};assert inv[1114]==26 and inv[561]==26 and inv[995]==30000
xp=next(x['xp'] for x in snap['stats'] if x['name']=='magic');assert xp==166701
text=(w/'run.log').read_text();passed=json.loads(next(l.split('PASS: live script_alcher ',1)[1] for l in text.splitlines() if l.startswith('PASS: live script_alcher ')));assert passed['outcome']=='PASS' and passed['scene']==2 and passed['tile']==[3185,3440,0]
probes=[json.loads(l) for l in (w/'window-responsiveness.jsonl').read_text().splitlines()];bad=[p for p in probes if not p['responsive']];assert len(probes)==225 and len(bad)==2 and all(p['elapsed_seconds']<4 for p in bad)
assert json.loads((w/'task-cleanup.json').read_text())['verified_absent']
result['windows_native']=dict(outcome='PASS',scope='Native 289 old-catalog Alcher core plus rendered internal screenshot, not full frontend controls',receipt=str((w/'receipt.json').relative_to(root)),binary_sha256=r['binary_sha256'],pass_evidence=passed,snapshot=str(snap_path.relative_to(root)),snapshot_sha256=sha(snap_path),magic_xp=xp,exact_inventory=inv,visual_observation='Root read internal PNG: rendered bank actor, scene2 panel and spellbook. Script paint still shows Alchs0 and Notes27 while paired snapshot has consumed item/rune and 30000 coins; do not use paint counters for work qualification.',probe_count=len(probes),startup_probe_failures=bad,probe_limits='Two visible HWNDs belonged to the process; one timed out twice within the first four seconds. Both responded through 59.78 seconds. Window titles/classes were not recorded, so loading/panel identity is unknown. No blanket responsiveness claim.',backend_limits='BOT_CPU omitted selects default rendering; no actual GPU adapter/backend identity in logs. No performance or CPU/GPU equivalence claim.',owned_scheduled_task_removed=True)
c=e/'concord-tui-6c7075ce';r=json.loads((c/'receipt.json').read_text());assert r['exit_code']==0 and r['process_exit_code']==0 and not r['runtime_error'] and sha(c/'terminal.log')==r['terminal_sha256']
rb=e/'linux-tui-6c7075ce';check=json.loads((rb/'root-check.json').read_text())
for p,h in check['downloaded_files'].items():assert sha(rb/p)==h,p
b=json.loads((rb/'binary.json').read_text());assert b['isolated_build'] and b['target_started_empty'] and b['binary_sha256']==r['binary_sha256'];assert check['verified_original_source_files']==2240
passed=json.loads(next(l.split('PASS: live alcher ',1)[1] for l in (c/'terminal.log').read_text(errors='replace').splitlines() if l.startswith('PASS: live alcher ')));inv={x['id']:x['count'] for x in passed['inv']};assert passed['outcome']=='PASS' and inv[1114]==26 and inv[561]==26 and inv[995]==30000
result['concord_tui']=dict(outcome='PASS',receipt=str((c/'receipt.json').relative_to(root)),binary_sha256=r['binary_sha256'],source_files=2240,private_entry_overlay=b['overlay'],pass_evidence=passed,scope='Actual PTY TUI 289 old-catalog Alcher core. Built on HyperV and copied to Concord with package hashes verified; no Concord compilation or Xvfb. Pause/Resume/Stop UI controls and revision274 remain separate.')
result['verified_at']=datetime.datetime.now(datetime.timezone.utc).isoformat();(e/'ui-qualification-6c7075ce.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({k:v['outcome'] for k,v in result.items() if isinstance(v,dict)}))
