import datetime,hashlib,json,os,pathlib,subprocess,sys,time
r=pathlib.Path(__file__).resolve().parents[2];rev=sys.argv[1];assert rev in ('274','289');short='7c2eef6e';e=r/'docs/compat/evidence';b=json.loads((e/f'catalog-headed/binary-paired-{short}.json').read_text());assert b['all_passed'];binary=pathlib.Path(b['binary']);assert hashlib.sha256(binary.read_bytes()).hexdigest()==b['binary_sha256'];engine=pathlib.Path('/Users/acfrazier/experiments')/('Server/engine' if rev=='274' else 'lostcity-289/engine');nav=r/'.superpowers/world-capabilities'/rev/'274bot.navpack';outdir=e/'paired-catalog-fixtures/live';outdir.mkdir(exist_ok=True);failed=[]
for case in ('air','duel'):
 for cat in ('100adccc037d9f6898080e1cad58fcfc43364775','8e7d965be2071d6ec65c3265e12af797082d720a'):
  out=outdir/f'r{rev}-{case}-{cat[:8]}-{short}';assert not out.with_suffix('.log').exists();env=os.environ.copy();env.update(LIVE='1',BOT_CPU='1',BOT_DEBUG='1',RUST_BACKTRACE='1',PAIRED_CATALOG_REVISION=rev,PAIRED_CATALOG_NAV_PACK=str(nav),PAIRED_CATALOG_NAV_FLAGS=str(nav.with_suffix('.navflags')),PAIRED_CATALOG_ROOT=str(r/'.superpowers/inputs'/f'rs2b0t-{cat}'),PAIRED_CATALOG_COMMIT=cat,PAIRED_CATALOG_ENGINE_DIR=str(engine));command=[str(binary),f'paired_catalog_{case}_live','--ignored','--exact','--nocapture'];start=time.monotonic();receipt=dict(case=case,revision=int(rev),catalog_commit=cat,host_commit=b['host_commit'],client_commit=b['client_commit'],binary_sha256=b['binary_sha256'],command=command,started_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),environment={k:v for k,v in env.items() if k.startswith('PAIRED_') or k in ('LIVE','BOT_CPU','BOT_DEBUG','RUST_BACKTRACE')},runner_sha256=hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest(),elapsed_is_not_performance_measurement=True)
  with out.with_suffix('.log').open('x') as log:
   process=subprocess.Popen(command,cwd=r,env=env,stdout=log,stderr=subprocess.STDOUT);receipt['pid']=process.pid;out.with_suffix('.process.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt),flush=True);code=process.wait()
  receipt.update(exit_code=code,finished_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),elapsed_seconds=round(time.monotonic()-start,3),log_sha256=hashlib.sha256(out.with_suffix('.log').read_bytes()).hexdigest(),engine_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=engine,text=True).strip(),nav_sha256=hashlib.sha256(nav.read_bytes()).hexdigest());out.with_suffix('.json').write_text(json.dumps(receipt,indent=2)+'\n');print(json.dumps(receipt),flush=True)
  if code:failed.append([case,cat,code]);break
print(json.dumps(dict(revision=rev,failed=failed)),flush=True);raise SystemExit(bool(failed))
