use api::snapshot::WorldTile;
use nav::{collision::WorldCollision, pack::{decode, encode}, router::{self, CostModel, FindOptions}, transport::TransportGraph, WorldState};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::{env, fs, hint::black_box, time::Instant};

const W: usize = 32;
const H: usize = 32;
const LEVELS: usize = 4;

#[derive(Serialize)] struct Phase { name: &'static str, elapsed_ns: u128, cpu_ns: u128, current_rss_bytes: Option<u64> }
#[derive(Serialize)] struct Output { status: &'static str, mode: String, input_bytes: usize, input_sha256: String, phases: Vec<Phase>, lookup_count: usize, route_count: usize, route_p99_ns: u128, route_ticks_sum: f64, capacities: Capacities, source: Source, selector_state_presets: Vec<u8>, limitations: Vec<&'static str> }
#[derive(Serialize)] struct Capacities { logical_cells: usize, blocked_words: usize, graph_edges: usize }
#[derive(Serialize)] struct Source { frozen_dense: &'static str, frozen_tiled: &'static str, frozen_client: &'static str, tool_commit: &'static str, host_head_at_build: &'static str, lock_sha256_at_build: &'static str }

fn rss() -> Option<u64> {
    if cfg!(target_os = "linux") {
        return fs::read_to_string("/proc/self/statm").ok()?.split_whitespace().nth(1)?.parse::<u64>().ok().map(|p| p * 4096);
    }
    let out = std::process::Command::new("ps").args(["-o", "rss=", "-p", &std::process::id().to_string()]).output().ok()?;
    String::from_utf8_lossy(&out.stdout).trim().parse::<u64>().ok().map(|k| k * 1024)
}
fn cpu_ns() -> u128 { unsafe { let mut r = std::mem::MaybeUninit::<libc::rusage>::uninit(); libc::getrusage(libc::RUSAGE_SELF, r.as_mut_ptr()); let r = r.assume_init(); (r.ru_utime.tv_sec as u128 * 1_000_000_000 + r.ru_utime.tv_usec as u128 * 1_000) + (r.ru_stime.tv_sec as u128 * 1_000_000_000 + r.ru_stime.tv_usec as u128 * 1_000) } }
fn phase<T>(out: &mut Vec<Phase>, name: &'static str, f: impl FnOnce() -> T) -> T { let t = Instant::now(); let c = cpu_ns(); let v = f(); out.push(Phase { name, elapsed_ns: t.elapsed().as_nanos(), cpu_ns: cpu_ns() - c, current_rss_bytes: rss() }); v }
fn fixture(mode: &str) -> Vec<u8> { let n = W * H * LEVELS; let mut walk = vec![0; n]; let mut blocked = vec![0; (n + 63) / 64]; if mode == "all-dense" { for i in 0..n { walk[i] = (i % 251) as u8; if i % 17 == 0 { blocked[i / 64] |= 1 << (i % 64); } } } let c = WorldCollision::from_packed_parts(WorldTile { x: 100, z: -20, level: 0 }, W, H, walk, blocked, None).expect("fixture shape"); encode(&c, &TransportGraph::default(), &[]) }
fn selectors(path: &str) -> Result<Vec<[i32; 10]>, String> { let mut out = Vec::new(); for (line_no, line) in fs::read_to_string(path).map_err(|e| e.to_string())?.lines().enumerate() { if line.trim().is_empty() { continue; } let v: Vec<i32> = line.split_whitespace().map(|x| x.parse().map_err(|_| format!("malformed selector line {}", line_no + 1))).collect::<Result<_, _>>()?; if v.len() != 10 || !(0..=3).contains(&v[2]) || !(0..=3).contains(&v[5]) || !(0..=15).contains(&v[6]) || !(0..=6).contains(&v[7]) || !(0..=4).contains(&v[8]) || !(0..=1).contains(&v[9]) { return Err(format!("unsupported selector line {}", line_no + 1)); } out.push(v.try_into().unwrap()); } if out.is_empty() { Err("selector file is empty".into()) } else { Ok(out) } }
fn state(preset: i32) -> WorldState { let mut s = WorldState::empty(); match preset { 4 => { s.stats.insert(6, 25); s.inv.insert(563, 50); s.inv.insert(556, 150); s.inv.insert(554, 50); }, 5 => { s.inv.insert(1712, 1); }, 6 => { s.inv.insert(995, 5000); }, 0..=3 => { if preset & 1 != 0 { s.stats.insert(6, 25); s.stats.insert(2, 3); s.quests.insert("Rune Mysteries".into()); s.quests.insert("é".into()); s.varps.insert(150, 160); } if preset & 2 != 0 { s.inv.insert(995, 10); s.worn.insert(1712); } }, _ => unreachable!() } s }
fn main() -> Result<(), String> { let mut args = env::args().skip(1); let mode = args.next().ok_or("usage: nav-stage-a all-uniform|all-dense ROUTES.tsv")?; if !matches!(mode.as_str(), "all-uniform" | "all-dense") { return Err("unsupported mode".into()); } let routes_file = args.next().ok_or("missing selector file")?; let selectors = selectors(&routes_file)?; let mut phases = Vec::new(); let bytes = phase(&mut phases, "retained_input", || fixture(&mode)); let input_bytes = bytes.len(); let hash = format!("{:x}", Sha256::digest(&bytes)); let (collision, graph, _) = phase(&mut phases, "decoded_converted", || decode(&bytes).map_err(|e| e.to_string()))?; let mut times = Vec::new(); let mut lookup_count = 0; let mut route_count = 0; let mut ticks = 0.0; phase(&mut phases, "hot_lookup_route", || { for v in &selectors { let from = WorldTile { x: v[0], z: v[1], level: v[2] }; let to = WorldTile { x: v[3], z: v[4], level: v[5] }; for _ in 0..8 { let start = Instant::now(); let model = if v[9] == 0 { CostModel::running() } else { CostModel { run_per_step: 1.0, walk_per_step: 1.0 } }; let opts = FindOptions { allow_teleports: v[6] & 1 != 0, allow_wilderness: v[6] & 2 != 0, allow_bank_fetch: v[6] & 4 != 0, essence: None }; let result = if v[9] == 0 { router::find_with(&collision, &graph, from, to, opts, &state(v[7])) } else { router::find_with_model(&collision, &graph, from, to, model) }; black_box(&result); if let Ok(route) = result { ticks += route.ticks; route_count += 1; } lookup_count += 1; times.push(start.elapsed().as_nanos()); } } }); times.sort_unstable(); let p99 = times[(times.len() * 99 / 100).min(times.len() - 1)]; let capacities = Capacities { logical_cells: collision.logical_cell_count(), blocked_words: collision.packed_blocked_words().count(), graph_edges: graph.edges.len() }; phase(&mut phases, "world_drop", || drop((collision, graph))); phase(&mut phases, "dropped_input", || drop(bytes)); phase(&mut phases, "post_drop", || black_box(rss())); println!("{}", serde_json::to_string(&Output { status: "synthetic_qualification_only", mode, input_bytes, input_sha256: hash, phases, lookup_count, route_count, route_p99_ns: p99, route_ticks_sum: ticks, capacities, source: Source { frozen_dense: "29b7aea779322c8611f83dc193e939ca7d756f75", frozen_tiled: "8385babb23fd15b876506d4a3f6154984a6b2df1", frozen_client: "3456edc8dabf7b25ada78110ffa56327af9f67a4", tool_commit: "760d3acbc429931447454af41902e43de8ac5b2e", host_head_at_build: env!("STAGE_A_HOST_HEAD"), lock_sha256_at_build: env!("STAGE_A_LOCK_SHA256") }, selector_state_presets: vec![0, 1, 2, 3, 4, 5, 6], limitations: vec!["synthetic input; no performance acceptance", "Darwin RSS is a direct ps sample, not ru_maxrss", "route workspace allocations are not collision-specific"] }).unwrap()); Ok(()) }
