"""Retain exact-source Chicken bank failures and their witness diagnosis."""
import hashlib,json,pathlib,subprocess
root=pathlib.Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],cwd=pathlib.Path(__file__).parent,text=True).strip());e=root/'docs/compat/evidence';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();m=json.loads((e/'catalog-headed/source-8fd0f138.json').read_text());b=json.loads((e/'catalog-headed/binary-headless-8fd0f138.json').read_text());assert b['isolated_build'] and sha(pathlib.Path(b['binary']))==b['binary_sha256']
for n,h in m['files'].items():assert sha(pathlib.Path(m['source_root'])/n)==h,n
rows=[]
for p in sorted((e/'catalog-harness/live').glob('*-chicken-killer-bank-*-8fd0f138.json')):
 r=json.loads(p.read_text());log=p.with_suffix('.log');text=log.read_text();assert r['exit_code']==1 and sha(log)==r['log_sha256'] and r['binary_sha256']==b['binary_sha256'];line=next(l for l in text.splitlines() if l.startswith('FAIL: catalog_boundary_live:'));assert 'runner=Passed' in line
 w=json.loads(line.split('core=',1)[1])['witness'];cycle=w['chicken_killer_bank_cycle'];a,z,d=w['baseline'],w['latest'],cycle['deposited'];assert a['levels']['attack']==a['levels']['strength']==30 and not a['item_ids'];assert cycle['combat_loot'] and d['bank_generation']==1 and d['bank_open'] and d['bank_loaded'] and d['bank_ids']['314']>=1 and not d['item_ids'];assert not cycle['returned'] and not cycle['further'];assert z['bank_generation']>d['bank_generation'] and z['xp']['strength']>d['xp']['strength']
 rows.append(dict(**{k:r[k] for k in ['host_commit','client_commit','catalog_commit','case','exit_code','elapsed_seconds']},revision=int(r['revision']),receipt=str(p.relative_to(root)),log=str(log.relative_to(root)),outcome='FAIL',build_provenance='Isolated8fd0f138 binary and all2411 source files reverified.',failure_class='fixture_closed_bank_generation_mismatch',diagnosis='Scenario runnerPassed and further melee XP observed. API IF_CLOSE advances bank_session_generation; core Chicken/Flax/Vial return check wrongly required equality with open deposit generation. Root correction requires a later generation; original failure remains unqualified pending a new run.',observed=dict(deposit_tick=d['tick'],deposit_generation=d['bank_generation'],deposit_feathers=d['bank_ids']['314'],deposit_strength_xp=d['xp']['strength'],latest_generation=z['bank_generation'],latest_strength_xp=z['xp']['strength'],runner='Passed',returned=False)))
assert len(rows)==2
p=e/'catalog-harness/core-results.json';ledger=json.loads(p.read_text());old={r['receipt'] for r in ledger};ledger.extend(r for r in rows if r['receipt'] not in old);p.write_text(json.dumps(ledger,indent=2)+'\n');(e/'catalog-harness/chicken-8fd0f138.json').write_text(json.dumps(dict(source_files_verified=len(m['files']),rows=rows),indent=2)+'\n');print(json.dumps(dict(failures=len(rows),ledger_rows=len(ledger))))
