//! Frozen-format parity for the paint strings.
//!
//! `paintLogic.js`, `levelProgress.js` and the Jive level rows are all served
//! by `load/paint_jive.rs`, and every string they produce must match the
//! reference rs2b0t sources byte for byte
//! (`reference/rs2b0t-00d39a17e0/src/bot/paint/{paintLogic,levelProgress}.ts`).
//! The expected column below was generated by running those sources under bun
//! (`String(n)` round-trips NaN and Infinity instead of collapsing them), and
//! the argument column is a JS expression, so an `undefined` argument stays
//! distinct from `null`.

use script::{LoadIsolate, LoadShape};

/// Every formatter the paint shim exports, re-exported for probing.
const BOT: &str = r#"
import { fmtDuration, fmtXpHr, paintSkillShort } from '../../paint/paintLogic.js';
import { xpAtLevel, levelProgress, etaHours, levelRow } from '../../paint/levelProgress.js';
globalThis.__f12 = { fmtDuration, fmtXpHr, paintSkillShort, xpAtLevel, levelProgress, etaHours, levelRow };
export default class T extends LoopingBot {}
"#;

fn spawn() -> LoadIsolate {
    LoadIsolate::spawn(BOT.to_string(), LoadShape::CompatClass, vec![]).expect("bot loads")
}

fn probe_str(iso: &LoadIsolate, expr: &str) -> String {
    iso.probe(expr)
        .unwrap_or_else(|e| panic!("probe {expr}: {e}"))
        .as_str()
        .unwrap_or_else(|| panic!("probe {expr} did not return a string"))
        .to_string()
}

/// `fmtDuration(mins)`: 0 ms, sub-second, hours, days, NaN, Infinity, undefined.
const DURATION: &[(&str, &str)] = &[
    ("0", "0:00:00"),
    ("0.0001", "0:00:00"),
    ("0.0166", "0:00:00"),
    ("0.1", "0:00:06"),
    ("0.5", "0:00:30"),
    ("0.999", "0:00:59"),
    ("1", "0:01:00"),
    ("1.5", "0:01:30"),
    ("59.5", "0:59:30"),
    ("59.999", "0:59:59"),
    ("60", "1:00:00"),
    ("61", "1:01:00"),
    ("90", "1:30:00"),
    ("119.5", "1:59:30"),
    ("1439", "23:59:00"),
    ("1440", "24:00:00"),
    ("100000", "1666:40:00"),
    ("1000000000", "16666666:40:00"),
    ("-5", "0:00:00"),
    ("NaN", "NaN:NaN:NaN"),
    ("Infinity", "Infinity:NaN:NaN"),
    ("undefined", "NaN:NaN:NaN"),
];

/// `fmtXpHr(gained, mins)`: the `—` cutoff, ties, negative, NaN, Infinity and
/// undefined rates.
const RATE: &[(&str, &str, &str)] = &[
    ("0", "0", "—"),
    ("0", "0.5", "—"),
    ("0", "0.6", "0.0k"),
    ("5", "6", "0.1k"),
    ("4000", "10", "24.0k"),
    ("250", "1", "15.0k"),
    ("1", "0.25", "—"),
    ("0.05", "1", "0.0k"),
    ("123456", "59.9", "123.7k"),
    ("5", "NaN", "NaNk"),
    ("5", "Infinity", "0.0k"),
    ("NaN", "10", "NaNk"),
    ("Infinity", "10", "Infinityk"),
    ("2.25", "3", "0.0k"),
    ("-100", "10", "-0.6k"),
    ("0.5", "0.25", "—"),
    ("1000000000", "1000000", "60.0k"),
    ("7", "0.6", "0.7k"),
    ("12", "1.2", "0.6k"),
    ("3", "2.5", "0.1k"),
    ("undefined", "10", "NaNk"),
    ("100", "undefined", "NaNk"),
];

/// `paintSkillShort(skill)`: the abbreviated table and the pass-through default.
const SKILL: &[(&str, &str)] = &[
    ("woodcutting", "WC"),
    ("firemaking", "FM"),
    ("fishing", "Fish"),
    ("cooking", "Cook"),
    ("mining", "Mine"),
    ("attack", "Att"),
    ("strength", "Str"),
    ("defence", "Def"),
    ("hitpoints", "HP"),
    ("ranged", "Range"),
    ("magic", "Mage"),
    ("prayer", "Pray"),
    ("crafting", "Craft"),
    ("smithing", "Smith"),
    ("herblore", "Herb"),
    ("agility", "Agil"),
    ("thieving", "Thief"),
    ("fletching", "Fletch"),
    ("runecraft", "RC"),
    ("slayer", "slayer"),
    ("farming", "farming"),
];

/// `xpAtLevel(level)`: the curve, its 1/99 clamp and an out-of-table index.
const XP_AT_LEVEL: &[(&str, &str)] = &[
    ("1", "0"),
    ("2", "83"),
    ("92", "6517253"),
    ("98", "11805606"),
    ("99", "13034431"),
    ("100", "13034431"),
    ("0", "0"),
    ("-3", "0"),
    ("1.5", "0"),
    ("NaN", "0"),
];

/// `levelProgress(level, xp)` as `level|fraction|remaining`.
const PROGRESS: &[(&str, &str, &str)] = &[
    ("1", "0", "1|0|83"),
    ("1", "1", "1|0.012048192771084338|82"),
    ("1", "83", "1|1|0"),
    ("1", "1154", "1|1|0"),
    ("1", "737627", "1|1|0"),
    ("1", "13034431", "1|1|0"),
    ("1", "13034432", "1|1|0"),
    ("1", "1000000000", "1|1|0"),
    ("1", "-5", "1|0|88"),
    ("1", "NaN", "1|NaN|NaN"),
    ("2", "0", "2|0|174"),
    ("2", "1", "2|0|173"),
    ("2", "83", "2|0|91"),
    ("2", "1154", "2|1|0"),
    ("2", "737627", "2|1|0"),
    ("2", "13034431", "2|1|0"),
    ("2", "13034432", "2|1|0"),
    ("2", "1000000000", "2|1|0"),
    ("2", "-5", "2|0|179"),
    ("2", "NaN", "2|NaN|NaN"),
    ("92", "0", "92|0|7195629"),
    ("92", "1", "92|0|7195628"),
    ("92", "83", "92|0|7195546"),
    ("92", "1154", "92|0|7194475"),
    ("92", "737627", "92|0|6458002"),
    ("92", "13034431", "92|1|0"),
    ("92", "13034432", "92|1|0"),
    ("92", "1000000000", "92|1|0"),
    ("92", "-5", "92|0|7195634"),
    ("92", "NaN", "92|NaN|NaN"),
    ("98", "0", "98|0|13034431"),
    ("98", "1", "98|0|13034430"),
    ("98", "83", "98|0|13034348"),
    ("98", "1154", "98|0|13033277"),
    ("98", "737627", "98|0|12296804"),
    ("98", "13034431", "98|1|0"),
    ("98", "13034432", "98|1|0"),
    ("98", "1000000000", "98|1|0"),
    ("98", "-5", "98|0|13034436"),
    ("98", "NaN", "98|NaN|NaN"),
    ("99", "0", "99|1|0"),
    ("99", "1", "99|1|0"),
    ("99", "83", "99|1|0"),
    ("99", "1154", "99|1|0"),
    ("99", "737627", "99|1|0"),
    ("99", "13034431", "99|1|0"),
    ("99", "13034432", "99|1|0"),
    ("99", "1000000000", "99|1|0"),
    ("99", "-5", "99|1|0"),
    ("99", "NaN", "99|1|0"),
    ("100", "0", "99|1|0"),
    ("100", "1", "99|1|0"),
    ("100", "83", "99|1|0"),
    ("100", "1154", "99|1|0"),
    ("100", "737627", "99|1|0"),
    ("100", "13034431", "99|1|0"),
    ("100", "13034432", "99|1|0"),
    ("100", "1000000000", "99|1|0"),
    ("100", "-5", "99|1|0"),
    ("100", "NaN", "99|1|0"),
    ("0", "0", "0|1|0"),
    ("0", "1", "0|1|0"),
    ("0", "83", "0|1|0"),
    ("0", "1154", "0|1|0"),
    ("0", "737627", "0|1|0"),
    ("0", "13034431", "0|1|0"),
    ("0", "13034432", "0|1|0"),
    ("0", "1000000000", "0|1|0"),
    ("0", "-5", "0|1|5"),
    ("0", "NaN", "0|1|NaN"),
    ("-3", "0", "-3|1|0"),
    ("-3", "1", "-3|1|0"),
    ("-3", "83", "-3|1|0"),
    ("-3", "1154", "-3|1|0"),
    ("-3", "737627", "-3|1|0"),
    ("-3", "13034431", "-3|1|0"),
    ("-3", "13034432", "-3|1|0"),
    ("-3", "1000000000", "-3|1|0"),
    ("-3", "-5", "-3|1|5"),
    ("-3", "NaN", "-3|1|NaN"),
    ("1.5", "0", "1.5|0|83"),
    ("1.5", "1", "1.5|0.012048192771084338|82"),
    ("1.5", "83", "1.5|1|0"),
    ("1.5", "1154", "1.5|1|0"),
    ("1.5", "737627", "1.5|1|0"),
    ("1.5", "13034431", "1.5|1|0"),
    ("1.5", "13034432", "1.5|1|0"),
    ("1.5", "1000000000", "1.5|1|0"),
    ("1.5", "-5", "1.5|0|88"),
    ("1.5", "NaN", "1.5|NaN|NaN"),
    ("NaN", "0", "NaN|1|0"),
    ("NaN", "1", "NaN|1|0"),
    ("NaN", "83", "NaN|1|0"),
    ("NaN", "1154", "NaN|1|0"),
    ("NaN", "737627", "NaN|1|0"),
    ("NaN", "13034431", "NaN|1|0"),
    ("NaN", "13034432", "NaN|1|0"),
    ("NaN", "1000000000", "NaN|1|0"),
    ("NaN", "-5", "NaN|1|5"),
    ("NaN", "NaN", "NaN|1|NaN"),
];

/// `etaHours(remaining, xpPerHour)`: null for a spent or idle rate, and the
/// caller's NaN back for a non-finite one.
const ETA: &[(&str, &str, &str)] = &[
    ("83", "24000", "0.0034583333333333332"),
    ("0", "100", "null"),
    ("-5", "100", "null"),
    ("100", "0", "null"),
    ("100", "-1", "null"),
    ("100", "NaN", "NaN"),
    ("100", "Infinity", "0"),
    ("NaN", "10", "NaN"),
    ("undefined", "100", "NaN"),
    ("100", "undefined", "NaN"),
];

/// `levelRow(gain, mins)` as `label|fraction|perHour|toGo|eta`.
const LEVEL_ROW: &[(&str, &str, &str)] = &[
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "0",
        "Craft 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "0.4",
        "Craft 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "0.5",
        "Craft 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "0.6",
        "Craft 1|0|0.0k/hr|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "1",
        "Craft 1|0|0.0k/hr|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "10",
        "Craft 1|0|0.0k/hr|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "59.9",
        "Craft 1|0|0.0k/hr|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "1440",
        "Craft 1|0|0.0k/hr|83 to go|eta n/a",
    ),
    (
        "{skill:'crafting',level:1,xp:0,gained:0}",
        "NaN",
        "Craft 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "0",
        "Mage 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "0.4",
        "Mage 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "0.5",
        "Mage 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "0.6",
        "Mage 1|0|400.0k/hr|83 to go|eta 0:00:00",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "1",
        "Mage 1|0|240.0k/hr|83 to go|eta 0:00:01",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "10",
        "Mage 1|0|24.0k/hr|83 to go|eta 0:00:12",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "59.9",
        "Mage 1|0|4.0k/hr|83 to go|eta 0:01:14",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "1440",
        "Mage 1|0|0.2k/hr|83 to go|eta 0:29:52",
    ),
    (
        "{skill:'magic',level:1,xp:0,gained:4000}",
        "NaN",
        "Mage 1|0|xp/hr n/a|83 to go|eta n/a",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "0",
        "Att 70|0|xp/hr n/a|76,818 to go|eta n/a",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "0.4",
        "Att 70|0|xp/hr n/a|76,818 to go|eta n/a",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "0.5",
        "Att 70|0|xp/hr n/a|76,818 to go|eta n/a",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "0.6",
        "Att 70|0|700.0k/hr|76,818 to go|eta 0:06:35",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "1",
        "Att 70|0|420.0k/hr|76,818 to go|eta 0:10:58",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "10",
        "Att 70|0|42.0k/hr|76,818 to go|eta 1:49:44",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "59.9",
        "Att 70|0|7.0k/hr|76,818 to go|eta 10:57:20",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "1440",
        "Att 70|0|0.3k/hr|76,818 to go|eta 263:22:33",
    ),
    (
        "{skill:'attack',level:70,xp:737627,gained:7000}",
        "NaN",
        "Att 70|0|xp/hr n/a|76,818 to go|eta n/a",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "0",
        "HP 99|1|xp/hr n/a|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "0.4",
        "HP 99|1|xp/hr n/a|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "0.5",
        "HP 99|1|xp/hr n/a|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "0.6",
        "HP 99|1|100.0k/hr|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "1",
        "HP 99|1|60.0k/hr|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "10",
        "HP 99|1|6.0k/hr|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "59.9",
        "HP 99|1|1.0k/hr|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "1440",
        "HP 99|1|0.0k/hr|maxed|",
    ),
    (
        "{skill:'hitpoints',level:99,xp:13034431,gained:1000}",
        "NaN",
        "HP 99|1|xp/hr n/a|maxed|",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "0",
        "Range 98|0.15819502370150346|xp/hr n/a|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "0.4",
        "Range 98|0.15819502370150346|xp/hr n/a|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "0.5",
        "Range 98|0.15819502370150346|xp/hr n/a|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "0.6",
        "Range 98|0.15819502370150346|0.0k/hr|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "1",
        "Range 98|0.15819502370150346|0.0k/hr|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "10",
        "Range 98|0.15819502370150346|0.0k/hr|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "59.9",
        "Range 98|0.15819502370150346|0.0k/hr|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "1440",
        "Range 98|0.15819502370150346|0.0k/hr|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'ranged',level:98,xp:12000000,gained:0}",
        "NaN",
        "Range 98|0.15819502370150346|xp/hr n/a|1,034,431 to go|eta n/a",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "0",
        "slayer 45|0|xp/hr n/a|6,471 to go|eta n/a",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "0.4",
        "slayer 45|0|xp/hr n/a|6,471 to go|eta n/a",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "0.5",
        "slayer 45|0|xp/hr n/a|6,471 to go|eta n/a",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "0.6",
        "slayer 45|0|2.0k/hr|6,471 to go|eta 3:14:07",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "1",
        "slayer 45|0|1.2k/hr|6,471 to go|eta 5:23:33",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "10",
        "slayer 45|0|0.1k/hr|6,471 to go|eta 53:55:30",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "59.9",
        "slayer 45|0|0.0k/hr|6,471 to go|eta 323:00:38",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "1440",
        "slayer 45|0|0.0k/hr|6,471 to go|eta 7765:12:00",
    ),
    (
        "{skill:'slayer',level:45,xp:61512,gained:20}",
        "NaN",
        "slayer 45|0|xp/hr n/a|6,471 to go|eta n/a",
    ),
];

#[test]
fn fmt_duration_matches_the_frozen_reference() {
    let iso = spawn();
    for (mins, want) in DURATION {
        let got = probe_str(&iso, &format!("String(__f12.fmtDuration({mins}))"));
        assert_eq!(got, *want, "fmtDuration({mins})");
    }
    iso.join();
}

#[test]
fn fmt_xp_hr_matches_the_frozen_reference() {
    let iso = spawn();
    for (gained, mins, want) in RATE {
        let got = probe_str(&iso, &format!("String(__f12.fmtXpHr({gained}, {mins}))"));
        assert_eq!(got, *want, "fmtXpHr({gained}, {mins})");
    }
    iso.join();
}

#[test]
fn paint_skill_short_matches_the_frozen_reference() {
    let iso = spawn();
    for (skill, want) in SKILL {
        let got = probe_str(&iso, &format!("String(__f12.paintSkillShort('{skill}'))"));
        assert_eq!(got, *want, "paintSkillShort({skill})");
    }
    iso.join();
}

#[test]
fn xp_at_level_matches_the_frozen_reference() {
    let iso = spawn();
    for (level, want) in XP_AT_LEVEL {
        let got = probe_str(&iso, &format!("String(__f12.xpAtLevel({level}))"));
        assert_eq!(got, *want, "xpAtLevel({level})");
    }
    iso.join();
}

#[test]
fn level_progress_matches_the_frozen_reference() {
    let iso = spawn();
    for (level, xp, want) in PROGRESS {
        let expr = format!(
            "(() => {{ const p = __f12.levelProgress({level}, {xp}); return [String(p.level), String(p.fraction), String(p.remaining)].join('|'); }})()"
        );
        let got = probe_str(&iso, &expr);
        assert_eq!(got, *want, "levelProgress({level}, {xp})");
    }
    iso.join();
}

#[test]
fn eta_hours_matches_the_frozen_reference() {
    let iso = spawn();
    for (remaining, rate, want) in ETA {
        let got = probe_str(
            &iso,
            &format!("String(__f12.etaHours({remaining}, {rate}))"),
        );
        assert_eq!(got, *want, "etaHours({remaining}, {rate})");
    }
    iso.join();
}

#[test]
fn level_row_matches_the_frozen_reference() {
    let iso = spawn();
    for (gain, mins, want) in LEVEL_ROW {
        let expr = format!(
            "(() => {{ const r = __f12.levelRow({gain}, {mins}); return [r.label, String(r.fraction), r.cells[0], r.cells[1], r.cells[2]].join('|'); }})()"
        );
        let got = probe_str(&iso, &expr);
        assert_eq!(got, *want, "levelRow({gain}, {mins})");
    }
    iso.join();
}
