"""Root qualification of reviewed real wrapper using generated bytes only."""
from pathlib import Path
import hashlib,json,shutil,sys,time
root=Path(__file__).resolve().parent;tool=root/'host/docs/memory/nav-tiled-differential'
sys.path.insert(0,str(tool));import harness as h
original=tool/'coordinate-native-generated-01';dest=tool/'coordinate-native-wrapper-generated-01'
binding=root/'host/docs/memory/nav-tiled-stage-a/coordinate-source-binding.json';digest='7b101c30bfd64c302815f9844fe27d3a52302feedaec58737726ab6a062491bb'
context=h.source_context(original,binding,digest)
assert json.loads((original/'result.json').read_text())['qualified']
dest.mkdir()
for arm in context['arms']:
 h.verify_arm(original,arm,context)
 shutil.copytree(original/arm,dest/arm,ignore=shutil.ignore_patterns('target'))
 binary=dest/arm/'target/debug/differential-probe';binary.parent.mkdir(parents=True);shutil.copy2(original/arm/'target/debug/differential-probe',binary)
 shutil.copy2(original/(arm+'-admission.json'),dest/(arm+'-admission.json'))
for n in ('launch.json','result.json','sources.json','source-binding.json'):
 if (original/n).exists():shutil.copy2(original/n,dest/n)
context=h.source_context(dest,binding,digest)
auth=dict(schema='nav-coordinate-differential-release-v1',candidate_id='coordinate-ebf0f30',source_binding=context['reference'],phase='native-release',mode='real',released=True,scope='Generated 337-byte input only; wrapper qualification, no private pack',limits=h.REAL)
for n in ('launch.json','result.json','sources.json'):auth[n+'_sha256']=h.sha(dest/n)
for arm in context['arms']:auth[arm+'_admission_sha256']=h.sha(dest/(arm+'-admission.json'))
guard=tool/'coordinate-native-guards-01/guards.json';pack=original/'inputs/routes-extension.bin';routes=original/'fixed.tsv'
auth.update(guard_report=str(guard),guard_report_sha256=h.sha(guard),input_path=str(pack),input_sha256=h.sha(pack),input_bytes=pack.stat().st_size,routes_path=str(routes),routes_sha256=h.sha(routes))
assert auth['input_bytes']==337
p=root/'coordinate-generated-wrapper-authorization.json';h.save(p,auth)
start=time.monotonic();h.real_run(dest,p,binding,digest)
r=json.loads((dest/'real-release/result.json').read_text());assert r['qualified']
out=dict(scope=auth['scope'],qualified=True,wall_seconds=time.monotonic()-start,authorization_sha256=h.sha(p),result=r,source_binding_sha256=digest)
h.save(root/'coordinate-generated-wrapper-result.json',out);print(json.dumps(out,indent=2))
