[package]
name = "e2e"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
host = { path = "../host" }
host-play = { path = "../host-play" }
vault = { path = "../vault" }
api = { path = "../api" }
nav = { path = "../nav" }
scenario = { path = "../scenario" }
client = { workspace = true }
