import { autoFoodBanking, shouldRestockFood, safeToSteal, foodMatches, withdrawTo, closeBankAndConfirmCount } from '*api/thieving/stealRules.js';
import { doseToDrink, acquireKey, teleportOut, bankRoutine } from '*api/combat/hunting/supply.js';
import { wantsDrop } from '*api/combat/hunting/logic.js';
import { muleGathererHandoffActive, muleReceiverActive, muleCookerActive, muleSupplierActive, muleNonGathererActive } from '*api/trade/PartnerTrade.js';
import { Trade } from '*api/trade/Trade.js';
import { eatAtHpThreshold, isFoodItem } from '*api/combat/food.js';
import { localFirePlot } from '*api/firemaking/Firemaking.js';
declare const host: Parameters<typeof acquireKey>[0];
declare const site: Parameters<typeof acquireKey>[1];
declare const filter: Parameters<typeof wantsDrop>[1];
const fixedWithdraw: Promise<number> = withdrawTo('Cake', 3, () => 1);
const fixedDefault: Promise<number> = withdrawTo('Cake', 3);
const fixedClose: Promise<boolean> = closeBankAndConfirmCount(3, () => 1);
const bankAuto: boolean = autoFoodBanking('Auto');
const restock: boolean = shouldRestockFood(true, 1, 2, false);
const safe: boolean = safeToSteal(0.5, 0.3, 1);
const matches: boolean = foodMatches(null, 'cake');
const dose: string | null = doseToDrink((_name: string) => 1);
const key: Promise<'held' | 'bank' | 'fetch'> = acquireKey(host, site);
const teleport: Promise<string | null> = teleportOut(host, site);
const bank: Promise<void> = bankRoutine(host, site, {withdrawFood: true});
const drop: boolean = wantsDrop({id: 1, name: 'Cake'}, filter);
muleGathererHandoffActive('gatherer', [], false);
muleReceiverActive('mule', []);
muleCookerActive('cooker', []);
muleSupplierActive('supplier', [], false);
muleNonGathererActive('mule', []);
Trade.offerAll('Cake');
Trade.offer('Cake', 1);
eatAtHpThreshold(10, 3);
isFoodItem(null, 'Cake');
localFirePlot({x: 1, z: 2, level: 0});
void fixedWithdraw;
void fixedDefault;
void fixedClose;
void bankAuto;
void restock;
void safe;
void matches;
void dose;
void key;
void teleport;
void bank;
void drop;
