param([Parameter(Mandatory=$true)][ValidatePattern('^native-render-owner-census-focused-plus-background-[A-Za-z0-9_.-]+$')][string]$CellId)
$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue'
$stage='C:\ProgramData\274bot-Test\renderer-owner-census-9268890'; if(-not(Test-Path $stage)){throw "Required stage missing: $stage"}
$vm=Get-VM -Name '274bot-builder'; if([string]$vm.State -ne 'Off'){throw 'Builder VM is not off'}
if(Get-Process cargo,rustc,panel-play,tui-play,qemu-system-x86_64,vmware-vmx -ErrorAction SilentlyContinue){throw 'Build/frontend/VM still running'}
$services=Get-Service DellTechHub,DellClientManagementService,ClickToRunSvc; if($services|Where-Object Status -ne 'Stopped'){throw 'Quiet services restarted'}
$drivers=Get-CimInstance Win32_VideoController|Select-Object Name,DriverVersion,PNPDeviceID
$launch=Get-Content 'C:\Users\BotTest\274bot-server-4c95f87\server-launch.json' -Raw|ConvertFrom-Json; $serverPid=[int]$launch.pid
$server=Get-CimInstance Win32_Process -Filter "ProcessId=$serverPid"; $listener=Get-NetTCPConnection -State Listen -LocalPort 43594
if(-not $server -or $server.Name -ne 'node.exe' -or @($listener|Where-Object OwningProcess -eq $serverPid).Count -ne 1){throw 'Fresh server identity not verified'}
if(Get-CimInstance Win32_Process|Where-Object {$_.Name -like 'Dell*' -or $_.Name -eq 'OfficeClickToRun.exe'}){throw 'Quiet process cleanup incomplete'}
Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public static class ConsoleSessionProbeOwnerCensus { [DllImport("kernel32.dll")] public static extern uint WTSGetActiveConsoleSessionId(); [StructLayout(LayoutKind.Sequential)] public struct SYSTEM_POWER_STATUS { public byte ACLineStatus; public byte BatteryFlag; public byte BatteryLifePercent; public byte Reserved; public int BatteryLifeTime; public int BatteryFullLifeTime; } [DllImport("kernel32.dll")] public static extern bool GetSystemPowerStatus(out SYSTEM_POWER_STATUS status); }'
$consoleSid=[ConsoleSessionProbeOwnerCensus]::WTSGetActiveConsoleSessionId(); $sessions=@(& quser.exe)
if(@($sessions|Where-Object {$_ -match ('^\s*bottest\s+console\s+'+$consoleSid+'\s+Active')}).Count -ne 1){throw 'BotTest local console is not active'}
if(Get-Process LogonUI -ErrorAction SilentlyContinue|Where-Object SessionId -eq $consoleSid){throw 'Console is locked'}
$processes=@(Get-CimInstance Win32_Process|Select-Object ProcessId,ParentProcessId,Name,SessionId,CreationDate,CommandLine)
$power=New-Object ConsoleSessionProbeOwnerCensus+SYSTEM_POWER_STATUS; if(-not [ConsoleSessionProbeOwnerCensus]::GetSystemPowerStatus([ref]$power)){throw 'GetSystemPowerStatus failed'}
$dxPath='C:\Users\BotTest\274bot-runs\display-routing-console-20260907\dxdiag-console.xml'; if(-not(Test-Path $dxPath)){throw 'Console DxDiag evidence missing'}
[xml]$dxXml=Get-Content $dxPath -Raw; $dx=@($dxXml.DxDiag.DisplayDevices.DisplayDevice|ForEach-Object{[ordered]@{cardName=[string]$_.CardName;driverVersion=[string]$_.DriverVersion;currentMode=if([string]$_.CurrentMode){[string]$_.CurrentMode}else{$null};hybridGraphicsGPU=if([string]$_.HybridGraphicsGPU){[string]$_.HybridGraphicsGPU}else{$null};monitorName=if([string]$_.MonitorName){[string]$_.MonitorName}else{$null}}}); if($dx.Count -eq 0){throw 'Console DxDiag contains no displays'}
$serverRecord=[ordered]@{ProcessId=[int]$server.ProcessId;ParentProcessId=[int]$server.ParentProcessId;Name=[string]$server.Name;SessionId=[int]$server.SessionId;CreationDate=[string]$server.CreationDate;CommandLine=$server.CommandLine}
$lasso=@($processes|Where-Object {$_.Name -match '(?i)^(ProcessLasso|bitsum|LassoGovernor).*\.exe$'})
$record=[ordered]@{schema='renderer-tile-probe-preflight-v1';purpose='Native N16 focused-plus-background TILE LAYOUT/OCCUPANCY diagnostic';cell_id=$CellId;stage=$stage;build_commit='9268890217d968cfeb7c66ebb11dd5c3dd2c084f';binary_sha256='e2deb1db371366f674c18e39d04f7309480310072ade224ffa1433c84d4559b5';count=16;adapter='Intel(R) Graphics';backgroundFps=1;utc=[DateTime]::UtcNow.ToString('o');powerState=[ordered]@{acLineStatus=[int]$power.ACLineStatus;activeScheme=@(& powercfg.exe /getactivescheme)};consoleSessionId=$consoleSid;vm=($vm|Select-Object Name,@{n='State';e={[string]$_.State}},@{n='MemoryAssigned';e={[int]$_.MemoryAssigned}});quietServices=@($services|Select-Object Name,@{n='Status';e={[string]$_.Status}});drivers=$drivers;sessions=$sessions;processes=$processes;processLasso=[ordered]@{running=(@($lasso).Count -gt 0);processes=$lasso};server=$serverRecord;dxdiag=$dx;dxdiagSource=[ordered]@{path=$dxPath;sha256=(Get-FileHash $dxPath -Algorithm SHA256).Hash.ToLower();kind='saved console observation, not a fresh scan'};strict_binding='9268890-only';performanceAcceptance=$false}
$record|ConvertTo-Json -Depth 10|Set-Content (Join-Path $stage ('preflight-tile-probe-'+$CellId+'.json')) -Encoding UTF8
'Preflight passed: frozen stage, console, power, quiet services, server, and display evidence recorded'
