import hashlib,json,pathlib,subprocess,sqlite3
root=pathlib.Path(subprocess.check_output(['git','rev-parse','--show-toplevel'],cwd=pathlib.Path(__file__).parent,text=True).strip());e=root/'docs/compat/evidence';rows=[];build=json.loads((e/'catalog-headed/binary-headless-6d750e65.json').read_text());assert build['isolated_build'] and hashlib.sha256(pathlib.Path(build['binary']).read_bytes()).hexdigest()==build['binary_sha256']
for p in sorted((e/'catalog-harness/live').glob('*6d750e65.json')):
 r=json.loads(p.read_text());log=p.with_suffix('.log');text=log.read_text();assert hashlib.sha256(log.read_bytes()).hexdigest()==r['log_sha256'];assert r['host_commit']==build['host_commit'] and r['binary_sha256']==build['binary_sha256']
 row={k:r[k] for k in ['host_commit','client_commit','catalog_commit','case','exit_code','elapsed_seconds']};row.update(revision=int(r['revision']),receipt=str(p.relative_to(root)),log=str(log.relative_to(root)),scope='Bronze/Steel recipe and newer-catalog alternative staff only; other supported settings and frontend acceptance remain separate.',build_provenance='New empty isolated target; frozen source hashes checked before and after build.')
 if r['exit_code']:
  assert r['case']=='superheater_fire_battlestaff' and 'could not wield Fire battlestaff' in text
  baseline=json.loads(next(l for l in text.splitlines() if l.startswith('{"phase":"baseline-after-preparation"')))['observation'];assert baseline['levels']['attack']==1
  row.update(outcome='FAIL',failure_class='fixture_missing_wield_requirement',failure_excerpt=[l for l in text.splitlines() if 'could not wield Fire battlestaff' in l or l.startswith('FAIL:')],diagnosis='Both selected tier30.rs2 sources require Magic 30 and Attack 30 for fire_battlestaff. Prepared Magic is 43 but Attack is 1. Correct and acknowledge Attack 30 before Start; preserve these failures and repeat only the two alternative-staff cells after a corrected fixture build.')
 else:
  c=json.loads(next(l.split('PASS: catalog_boundary_live: ',1)[1] for l in text.splitlines() if l.startswith('PASS: catalog_boundary_live: ')))['core'];a,z,cycle=c['baseline'],c['latest'],c['superheater_cycle'];d,w=cycle['deposited'],cycle['withdrawn'];steel=r['case']=='superheater_steel';bar,pri,sec,ratio=('2353','440','453',2) if steel else ('2349','436','438',1)
  assert a['ingame'] and z['ingame'] and a['scene_state']==z['scene_state']==2 and not a['item_ids'] and not a['equipment_ids'];assert cycle['first_bars'] and cycle['produced_after_withdrawal'] and not cycle['wrong_product'] and not cycle['wrong_staff'];assert d['bank_open'] and d['bank_loaded'] and d['bank_generation']>a['bank_generation'];assert w['bank_loaded'] and w['bank_generation']==d['bank_generation'];assert d['bank_ids'][bar]>0 and w['item_ids'][sec]==ratio*w['item_ids'][pri];assert d['tick']<w['tick']<z['tick'];assert z['item_ids'][bar]>0 and z['item_ids'][pri]<w['item_ids'][pri] and z['item_ids'][sec]<w['item_ids'][sec] and z['item_ids']['561']<w['item_ids']['561'];assert z['equipment_ids']['1387']==1 and not z['bank_open'];assert all(z['xp'][skill]>w['xp'][skill]>a['xp'][skill] for skill in ['magic','smithing']);row.update(outcome='PASS',cycle=cycle,xp_delta={k:z['xp'][k]-a['xp'][k] for k in ['magic','smithing']},latest_item_ids=z['item_ids'],post_start_observations=c['post_start_observations'])
 rows.append(row)
assert len(rows)==10 and sum(r['outcome']=='PASS' for r in rows)==8
p=e/'catalog-harness/core-results.json';ledger=json.loads(p.read_text());old={r['receipt'] for r in ledger};ledger.extend(r for r in rows if r['receipt'] not in old);p.write_text(json.dumps(ledger,indent=2)+'\n');(e/'superheater-fixtures/isolated-results-6d750e65.json').write_text(json.dumps(rows,indent=2)+'\n')
p=root/'docs/compat/support-matrix.json';matrix=json.loads(p.read_text())
for cell in matrix['rows']:
 if cell['display_name']!='Superheater':continue
 selected=[r for r in rows if r['revision']==cell['revision'] and r['catalog_commit']==cell['catalog_commit']];assert len([r for r in selected if r['outcome']=='PASS'])==2;cell['status']='PARTIAL';cell['fixture_readiness']='Bronze and Steel complete isolated full bank/production cycles; alternative staff fixture correction pending.';cell['status_detail']='Core Bronze and Steel show actual staff equip, exact ore/rune consumption, bars, Magic/Smithing XP, deposit/restock and further production. Newer-catalog alternative Fire battlestaff cells were seeded with Attack 1 instead of required 30 and failed honestly at wield; this is a fixture defect, not a script/card defect.';cell['proof_refs']=list(dict.fromkeys(cell.get('proof_refs',[])+[v for r in selected for v in [r['receipt'],r['log']]]+['docs/compat/evidence/superheater-fixtures/isolated-results-6d750e65.json']))
p.write_text(json.dumps(matrix,indent=2)+'\n')
facts=[]
for base in ['Server','lostcity-289']:
 path=pathlib.Path('/Users/acfrazier/experiments')/base/'content/scripts/levelrequire/scripts/tier30.rs2';line=path.read_text().splitlines()[77];assert line=='[opheld2,fire_battlestaff] @levelrequire_magic_and_attack(30, 30, last_slot);';facts.append(dict(path=str(path),line=78,text=line,sha256=hashlib.sha256(path.read_bytes()).hexdigest(),content_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=path.parents[3],text=True).strip()))
(e/'superheater-fixtures/fire-battlestaff-wield-requirement.json').write_text(json.dumps(facts,indent=2)+'\n')
c=sqlite3.connect('file:/Users/acfrazier/.hermes/kanban/boards/274bot/kanban.db?mode=ro',uri=True);c.row_factory=sqlite3.Row;r=dict(c.execute('select * from task_runs where id=1215').fetchone());r['metadata']=json.loads(r['metadata']);assert r['metadata']['reviewer_model']=='grok-4.5';(e/'coordinate-reachability/review.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps(dict(cells=len(rows),pass_cells=8,failed_fixture_cells=2,ledger_rows=len(ledger))))
