param([Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9_-]+$')][string]$CellId,[Parameter(Mandatory=$true)][string]$Destination)
$ErrorActionPreference='Stop'; $run=Join-Path 'C:\Users\BotTest' ('274bot-runs\managed-tile-boxed-'+$CellId); if(-not(Test-Path $run)){throw 'Run directory missing'}; $completion=Join-Path $run 'completion.json'; $completionPresent=Test-Path $completion; $receipt=$null;if($completionPresent){$receipt=Get-Content $completion -Raw|ConvertFrom-Json}
$dest=Join-Path $Destination $CellId;if(Test-Path $dest){throw 'Archive exists; preserve prior output'};New-Item -ItemType Directory -Path $dest|Out-Null; $managed=Join-Path $dest 'managed-run';New-Item -ItemType Directory -Path $managed|Out-Null;Copy-Item (Join-Path $run '*') $managed -Recurse -Force
$rawSources=@();foreach($rp in @(Get-ChildItem $run -Recurse -File -Filter receipt.json -ErrorAction SilentlyContinue)){try{$r=Get-Content $rp.FullName -Raw|ConvertFrom-Json;if($r.run_dir){$rawSources+=[string]$r.run_dir}}catch{}};if($receipt -and $receipt.run_dir){$rawSources+=[string]$receipt.run_dir};$rawSources=@($rawSources|Sort-Object -Unique);$rawRecords=@();$i=0
foreach($raw in $rawSources){if(Test-Path $raw -PathType Container){$i++;$rd=Join-Path $dest ('raw-run-{0:d2}'-f $i);New-Item -ItemType Directory -Path $rd|Out-Null;Copy-Item (Join-Path $raw '*') $rd -Recurse -Force;$rawRecords+=[ordered]@{source=$raw;archive=$rd;present=$true}}else{$rawRecords+=[ordered]@{source=$raw;archive=$null;present=$false}}}
$log=Join-Path 'C:\Users\BotTest\274bot-runs' ('managed-tile-boxed-'+$CellId+'-launcher.log');$lr=$null;if(Test-Path $log){$ld=Join-Path $dest 'launcher.log';Copy-Item $log $ld -Force;$lr=[ordered]@{source=$log;archive=$ld}}
$files=Get-ChildItem $dest -File -Recurse|Sort-Object FullName|ForEach-Object{[ordered]@{path=$_.FullName.Substring($dest.Length+1);sha256=(Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLower();length=$_.Length}}
$manifestPath=Join-Path $dest 'archive-manifest.json';[ordered]@{schema='tile-boxed-archive-v1';cell_id=$CellId;archive=$dest;sourceRun=$run;completionPresent=$completionPresent;receiptExitCode=if($receipt){$receipt.exit_code}else{$null};receiptStatus=if($receipt){$receipt.status}else{$null};rawRuns=$rawRecords;launcherLog=$lr;files=$files;performanceAcceptance=$false;note='Failed or incomplete evidence is retained; receipt status is not qualification.'}|ConvertTo-Json -Depth 10|Set-Content $manifestPath -Encoding UTF8
Get-FileHash $manifestPath -Algorithm SHA256
