// Generated by tools/game-data/generate.ts from pinned rs2b0t cook sources; do not curate.
pub const MAX_SURFACE_CHEB: i32 = 20;
pub const DERIVED_ARRIVE_RADIUS: i32 = 2;
pub const DEFAULT_OBSTACLES: &[&str] = &["door", "gate"];
pub const COOK_CAMPS: &[CookCamp] = &[
    CookCamp { bank: "Catherby", stand: WorldTile { x: 2817, z: 3443, level: 0 }, approach: None, loc: WorldTile { x: 2817, z: 3444, level: 0 }, loc_name: "Range", kind: CookSurfaceKind::Oven, label: "Catherby range (bank house)" },
    CookCamp { bank: "Seers", stand: WorldTile { x: 2716, z: 3477, level: 0 }, approach: Some(WorldTile { x: 2713, z: 3484, level: 0 }), loc: WorldTile { x: 2715, z: 3476, level: 0 }, loc_name: "Range", kind: CookSurfaceKind::Oven, label: "Seers village range (near bank)" },
    CookCamp { bank: "Draynor", stand: WorldTile { x: 3100, z: 3257, level: 0 }, approach: Some(WorldTile { x: 3102, z: 3258, level: 0 }), loc: WorldTile { x: 3100, z: 3256, level: 0 }, loc_name: "Fireplace", kind: CookSurfaceKind::Fire, label: "Draynor house fireplace" },
];
