import datetime,hashlib,json,os,pathlib,plistlib,shutil,subprocess,time
root=pathlib.Path(__file__).resolve().parents[2]; out=root/'docs/compat/evidence/loadout-capabilities/native-ui-50f2be8a'; manifest=json.loads((out/'source.json').read_text()); source=pathlib.Path(manifest['source_root']); target=root/'.superpowers/loadout-ui/target-isolated-50f2be8a'; assert not target.exists(); env=dict(os.environ);env.update(CARGO_TARGET_DIR=str(target),GIT_COMMIT=manifest['host_commit'],GIT_DIRTY='0')
for name,h in manifest['files'].items(): assert hashlib.sha256((source/name).read_bytes()).hexdigest()==h,name
for label,args in [('tests',['test','-p','panel','--lib','loadout']),('build',['build','-p','panel','--example','startup_watch','--message-format=json'])]:
 stem=out/label; assert not stem.with_suffix('.log').exists(); start=time.monotonic(); command=['cargo']+args
 with stem.with_suffix('.stdout').open('w') as stdout, stem.with_suffix('.log').open('w') as stderr:
  p=subprocess.Popen(command,cwd=source,env=env,stdout=stdout,stderr=stderr);print(json.dumps(dict(label=label,pid=p.pid,command=command)),flush=True); code=p.wait()
 for name,h in manifest['files'].items(): assert hashlib.sha256((source/name).read_bytes()).hexdigest()==h,name
 record=dict(command=command,exit_code=code,source_root=str(source),host_commit=manifest['host_commit'],client_commit=manifest['client_commit'],cargo_target_dir=str(target),isolated_build=True,target_started_empty=True,source_files_verified=len(manifest['files']),elapsed_seconds=round(time.monotonic()-start,3));stem.with_suffix('.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record),flush=True)
 if code:raise SystemExit(code)
rows=[json.loads(line) for line in (out/'build.stdout').read_text().splitlines()]; bins=[r['executable'] for r in rows if r.get('reason')=='compiler-artifact' and r.get('target',{}).get('name')=='startup_watch' and r.get('executable')]; assert len(bins)==1; app=root/'.superpowers/loadout-ui/Loadout UI Proof.app'; mac=app/'Contents/MacOS';mac.mkdir(parents=True);binary=mac/'startup_watch';shutil.copy2(bins[0],binary);(app/'Contents/Info.plist').write_bytes(plistlib.dumps(dict(CFBundleExecutable='startup_watch',CFBundleIdentifier='dev.274bot.loadout-ui-proof',CFBundleName='274bot Loadout UI Proof',CFBundlePackageType='APPL',NSHighResolutionCapable=True)));record.update(binary=str(binary),binary_sha256=hashlib.sha256(binary.read_bytes()).hexdigest(),scope='Private native UI entry uses existing IsolatedEnv; product source unchanged from named commit',signed=False);(out/'binary.json').write_text(json.dumps(record,indent=2)+'\n');print(json.dumps(record),flush=True)
